Feat/confirmar devolucao
PoweredTable/sist-emprestimo-de-ferramentas pull request #70
Opened 2024-05-27 00:29 UTC by LucasPeixer

Solicito que seja colocado a branch Feat/confirmar-devolucao na branch dev.

2024-05-27 22:42 UTC, WRbosss approved these changes

2024-05-27 22:50 UTC, PoweredTable requested changes

2024-05-27 22:50 UTC, PoweredTable commented on src/main/java/visao/TelaPrincipal.java
>  import controle.EmprestimoControle;
Duplo import de `EmprestimoControle`

2024-05-30 18:23 UTC, PoweredTable approved these changes

2024-05-30 18:23 UTC, merged